[features]
seeds = false
skip-lint = false
[programs.localnet]
hello_world = "81BZshqgucT57iAw4kgPZiGpApZS4LbBzTXT2UMEAzod"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "C:\\Users\\gadre\\.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
